### ISSUE TITLE
Show if method/event/param/whatever is deprecated

### ISSUE THREAD

**Issue by ghost** [kozubikmichal/vscode-ui5-explorer#13]
Hi,

thank you for this great extension. I use it daily, however there is some small issue which could be improved imo: **Deprecated** stuff.

How I see it in your extension:

![image](https://user-images.githubusercontent.com/65161626/90906137-780cdb80-e3d1-11ea-964a-f5a229e57dfd.png)

How I see it in the official docs:

![image](https://user-images.githubusercontent.com/65161626/90906200-8fe45f80-e3d1-11ea-8432-d4b083cd492f.png)

Can you add some information (maybe even a small ❌ emoji?) to highlight deprecated things?

Best regards!

**Comment by kozubikmichal** [comment]
Hi @OTTOxMarc 

Thanks for the idea! I will add the support for this during next few days.

Regards
Michal

**Comment by kozubikmichal** [comment]
Please checkout the 0.5.0 version and let me know if you should find any issue.
