### ISSUE TITLE
Request failed with status code 407

### ISSUE THREAD

**Issue by dev-oskar** [kozubikmichal/vscode-ui5-explorer#14]
I'm struggling with configuration and usage of the extension. 
I am using newest VS Code version (1.50.0) and the extension's newest version as well (0.5.0).

After installation I am unable to open the extension panel on the left side and there this popup appears with following message:
"Request failed with status code 407". I am unable to see any of the documentation. I have an access in browser to both 
- OpenUI5: "https://openui5.hana.ondemand.com"
- SAPUI5: "https://sapui5.hana.ondemand.com"

**Comment by kozubikmichal** [comment]
Hi @keyboard-samurai!

It seems you are behind some (corporate) proxy, is that right? In case the rest of base VSCode functionality works OK (eg. fetching and installing extensions), could you please try to enable proxy support also for extensions?

https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions

**Comment by dev-oskar** [comment]
Unfortunately it didn't work. I've enabled the Http proxy support and reloaded the VS Code, but it is still returning 407 error code. 

Yes, I am behind corporate proxy. Fetching and installing extensions are working correctly, cloning the extension's repository with git works as well. I've also tried switching to the Http proxy support "**off**" but then the returned error is _getaddrinfo ENOTFOUND openui5.hana.ondemand.com_

**Comment by kozubikmichal** [comment]
Did you also set the `http.proxy` in the settings file?

**Comment by dev-oskar** [comment]
I have not.
How should I configure it?

**Comment by kozubikmichal** [comment]
Yes please, according to the VSCode documentation the editor itself takes the proxy settings from the system. But it does not pass those settings to the extensions directly and therefore this has to be set separately

see https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support

**Comment by dev-oskar** [comment]
I think I've set it properly, but it still isn't working. I guess it's connected somehow with firewall and our company's policy, or I have messed something up during the configuration. It seems like I will still be using chrome version of the docs. Thanks anyway! Cheers

**Comment by kozubikmichal** [comment]
@keyboard-samurai I will try to investigate it but first I have to figure out how to reproduce it. I am also behind corporate proxy and my only setting is
```"http.proxyStrictSSL": false```
and nothing else.

Also you can open the extension outside the company network and try to load several pages from different libraries (sap.m, sap.f...). After the first load those libraries are stored in file system so the next time they are loaded without external http request.

**Comment by dev-oskar** [comment]
Thanks, I will try these settings as well.
There is also a possibility to load libraries from file instead of URL, maybe there's a way to configure it properly.
