### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by 29Esther** [kozubikmichal/vscode-ui5-explorer#2]
Hi, 
how to determine the version of the UI5 api I am looking at?
Thanks & Regards,
Esther

**Comment by kozubikmichal** [comment]
Hi Esther,

currently there is no way how to set specific UI5 version. But I plan to add configuration entry to support this. It could be part of the next release coming out in few weeks.

Regards
Michal

**Comment by 29Esther** [comment]
Thank you, Michal.
