### ISSUE TITLE
Receiving "read ECONNRESET" for any version

### ISSUE THREAD

**Issue by maboumra** [kozubikmichal/vscode-ui5-explorer#4]
Hi, I don't know if this is an issue with the extension but I am receiving this message for any version of SAPUI5 or OpenUI5, old or new, and the docs don't download. I am posting an issue here in the hope that someone can help me.

Thanks in advance.

**Comment by maboumra** [comment]
I don' know if it helps but my proxy is emitting the following message:
"HEAD: ♥headers_recv: Unknown header (♥)

**Comment by kozubikmichal** [comment]
Hi @maboumra ,

It seems like some general issue, not extension relevant. Do you have some specific proxy applied in VSCode? Are you able to access this page in your browser: https://openui5.hana.ondemand.com?

Regards
Michal

**Comment by maboumra** [comment]
Hi Michal! I was suspicious it was a proxy problem. Unfortunately I have to use cntlm at the work. I will try again at home. Thank you!
