### ISSUE TITLE
No API reference tree

### ISSUE THREAD

**Issue by dan-hg** [kozubikmichal/vscode-ui5-explorer#7]
Dear kozubikmichal!

I have some problem to use your ui5 explorer extension. 
The API reference tree is almost empty, I made a screenshot:
<img width="814" alt="Screenshot 2019-12-06 at 11 33 20" src="https://user-images.githubusercontent.com/58592374/70317016-36c1a500-181d-11ea-995d-08ee589ef31c.png">

Iam on mac osx Catalina (latest), and VS code  1.40.2 (latest). I have tried to re-install the extension, it does not work....

Coulld you please help me?
Thank you!

**Comment by kozubikmichal** [comment]
Hi dan,
there were some api changes in 1.63, I have to adjust the extension. Unfortunatelly I had no time to maintain the extension. Please keep in touch, new vesion should be available during next days.

Regards
Michal

**Comment by kozubikmichal** [comment]
Hi @dan-hg 
Please see the latest version 0.4.0 - this version adds support for UI5 >=1.63

Regards
Michal

**Comment by dan-hg** [comment]
Dear Michal,

Great it solved the problem.
Thank you for your work!

Regards
Daniel
